Reorganise Telegram page
HACManchester/documentation pull request #39
Opened 2023-02-04 13:20 UTC by rjackson

**Context**

As raised in our January 2023 Members Meeting, we have numerous Telegram group chats. Some of which are linked to from the docs site, some of which are referenced in pinned messages, and others which may be nested in other group's pinned messages.

The breadth of chats we have any the many different places we link to them pose a discoverability problem.

To improve the new membership experience, I'll be proposing many changes on a member's dashboard later on – including a link to this Telegram page. Before I progress that, I wanted to give this page a tidy up first.

**Changes**

I've approached this by rewriting the page top-to-bottom, introducing some formatting and tables to – hopefully – make the page easier to read.

I've also completely removed the original list of channels, as many of the links appeared to have expired, and instead taken the latest list from the pinned message last-updated on Jan 28th 2023.

We may have more Telegram channels than are listed here. If there are any more that I've missed – because I'm not aware of them – please do let me know.

For some of our private operational-related channels, whilst they're not open for members to freely join I would prefer we list them on this page – just without an invite link. I do think it would be helpful to have one centralised, complete list of our Telegram groups.

**devcontainer.json file**

This PR also contains a `devcontainer.json` file. This is a developer-related configuration which makes it easier to run the docs system in a development environment.

This file has no impact on the final, deployed, documentation site.

**Preview**

Whilst we are hosted on Github Pages, I don't think we are able to have PR-specific preview builds.

Instead, I've temporarily deployed a build of the docs site on my own Netlify account.

[See a preview of the new Telegram page](https://delicate-gumdrop-a6d75a.netlify.app/telegram/)

2023-02-04 13:32 UTC, conorriches requested changes
Looking really good overall, couple of minor points

2023-02-04 13:32 UTC, conorriches commented on docs/Telegram.md
> +You will need a phone number to sign up for Telegram. This is kept private and hidden from other Telegram users by default.
I love the more detailed explanation of Telegram. One thing to add maybe as I know a few people (me included) got really pissed off that Telegram blabbed to everyone that I joined:


```suggestion
You will need a phone number to sign up for Telegram. This is kept private and hidden from other Telegram users by default.

Please note that when you join Telegram, people with your phone number in their address book will be notified that you joined Telegram. 
```

2023-02-04 13:32 UTC, conorriches commented on docs/Telegram.md
> +| [Laser Training](https://t.me/joinchat/D5l4WUNG_uyg6YB0PYikRA) | To coordinate Laser training sessions between trainers and those waiting to be inducted.                             |
This is going against the previous system where people would request an induction on the membership system, and the tool page would then present this link to them. This ensured that a training record was created appropriately.

2023-02-04 13:32 UTC, conorriches commented on docs/Telegram.md
> +| [Laser Training](https://t.me/joinchat/D5l4WUNG_uyg6YB0PYikRA) | To coordinate Laser training sessions between trainers and those waiting to be inducted.                             |
```suggestion
| Laser Training | To coordinate Laser training sessions between trainers and those waiting to be inducted. Please request an induction on the membership system first, which will then give you the link to join.                             |
```

2023-02-04 14:34 UTC, rjackson commented
Thanks @conorriches, great feedback! I've made some tweaks accordingly :)

[The same preview page](https://delicate-gumdrop-a6d75a.netlify.app/telegram/) has also been updated.

2023-02-04 15:02 UTC, conorriches approved these changes

2023-02-04 15:22 UTC, chris18890 approved these changes

2023-02-05 17:15 UTC, rjackson commented
Thank you both :)

2023-02-05 17:15 UTC, merged